[theme]
base="light"

primaryColor="#0F172A"                # Bleu ardoise profond (accent sérieux)
backgroundColor="#F8FAFC"             # Gris très clair neutre
secondaryBackgroundColor="#115cbd"    # Gris doux pour blocs / sidebar
textColor="#0B1220"                   # Presque noir, plus dense
font="sans serif"

[client]
showSidebarNavigation = false
